config/MovingWorld/Main.cfg
config/betterwithmods.cfg
config/charm.cfg
scripts/betterwithmods_recipes_craftingtable.zs
scripts/harvestcraft.zs
scripts/mcwbridges.zs
scripts/shields_baubles.zs
scripts/spartan.zs

Makes it a bit more interesting and uses ore dictionary to accept any stone instead of vanilla only

Various things, actually

---

scripts/future-mc.zs

The recipes from the Blast Furnace doesn't have compatibility yet, this currently only is for the Stonecutter.

Added Underground Biome Stones to FutureMC's Stonecutter

---

config/coralreef.cfg
config/sereneseasons/biome_info.json

Undid what I just added minus tips

Undid Season changes & Coral Reef

---

config/coralreef.cfg
config/dsurround/dsurround.cfg
config/sereneseasons/biome_info.json
config/watercontrolextreme.cfg

Seasonal biomes and infinite water for more biomes

Biome & Water Changes

---

config/triumph/script/triumph/advancements/setbonuses/moltenarmor.txt
config/triumph/script/triumph/advancements/setbonuses/myrmexarmor.txt
scripts/endreborn.zs

Also removes an unused variable `test`

Make myrmex and molten armor mid-game

---

scripts/electrumRework_aetherEnchanter.zs

Remove metadata from the steel_sword
Not sure if it'll actually work though since I can't test it, but it's the only thing that looks off

Should fix trans sword repair

---

resourcepacks/Better Rebirth 1.12.2/assets/netherex/lang/en_us.lang
scripts/biomesoplenty.zs

Add correct pigtificate chief name
Remove biome finder recipe
Change bop amethyst block recipe to only use bop amethysts, allows nether amethyst blocks to be crafted

Minor fixes

---

config/tool_progression/block_overwrites.cfg

Fix stone brick walls

---

resourcepacks/Better Rebirth 1.12.2/assets/iceandfire/loot_tables/ice_dragon_cave.json

Fix comment of #269 (I dunno if this'll close it)

Change iceandfire sapphire to bop sapphire

---

scripts/pyrotech/pyrotech_recipes_kiln.zs

Add ender slag recipe to brick kiln only with 70% chance of getting ender slag

Fix ender slag

---

scripts/pyrotech/pyrotech_recipes_kiln.zs

Reverts CalaMariGold/Rebirth-Of-The-Night#343

Revert "Fix ender slag"

---

README.md

this is demo edit

---

scripts/jei_descriptions.zs

i just wanted to edit it on github online

Add apiary description

---

config/setbonus/1.12.2.009+.cfg

Better w/ Mods' fortune effect is glitched and doesn't work with dynamic trees, so I replaced it with the wards fortune effect which does work.

Updated Fortune Effects

---

scripts/pyrotech/pyrotech_recipes_other.zs

Changed the i/o on the recipe to fix the issue. Removed the *8 multiplier on both powder and resultant concrete.

Fixed Concrete Soaking Pot Dupe

---

scripts/pyrotech/pyrotech_recipes_craftingtable.zs

why tf am i on this account

---

scripts/betterwithmods/betterwithmods.zs

Fixes the following issues:
- Unfired vase -> Unfired pot recipe fixed (no longer requires fired version + removed clay ball drop for balance)
- Added Unfired urn -> Clay ball recipe

Fixes #629

---

scripts/foundry_ceramics.zs

IT WORKED LETS FUCKING GOOOOOOOOOOOO cwong is a big cutie btw

Added All Stoked Flame Blockstates to Foundry Heating

---

scripts/wood_stripping_boards.zs

Fixed Cherry Wood Nailed Planks

---

config/antiqueatlas/atlas_overlay.cfg

Tweaked Atlas position

---

config/setbonus/1.12.2.009+.cfg

https://discord.com/channels/620840315498004480/714540497171120199/815726720400883733

Troll armor set nerf: First attempt™️

---

config/GeographiCraft/geographicraft.cfg

ye, just increases continent size and reduces ocean size simultaneously

geographicraft.cfg change to shrink oceans

---

ambience_music/ambience.properties

winter's night is in the music folder but does not show up in game at all. as with 2.77.5, it will now play in snowy biomes and during night.

adding unused track, Winter's Night, to play in snowy biomes and during night

---

scripts/events.zs

Double-right click is likely still a problem with these buckets
Part of #591

Fix other buckets not working with well

---

config/horsepower.cfg

updated entity ids to correct ids used in game for horse powered items

horsepower fixes

---

config/customloadingscreen_tips.txt
config/loadingscreens/LoadingScreens.txt

Evil coders tricking innocent players into feeling safe 
https://github.com/Rebirth-of-the-Night/Rebirth-of-the-Night/blob/4953335192e9c389e3abfcd9c1ce1b9e50ff2c1e/hordes.cfg#L22-L23

Corrects "invasions every 17 days" to "every 15 days" in tips
